In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [9]:
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [10]:
a = np.exp(2)
print(a)

7.38905609893065


In [13]:
arr = np.array([28, 30, 29, 31, 32, 30, 29])
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(arr[arr>30].size)

29.857142857142858
32
28
2


In [15]:
arr = np.array([85, 90, 78, 92, 88])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(arr/10)

86.6
88.0
4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [23]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a+b)
print(a*b)
print(a@b)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [34]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print(np.max(arr, axis=0))
print(np.min(arr, axis=1))
print(np.where(arr%2!=0, -1, arr))
arr[arr%2==1] = -1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [12]:
arr = np.arange(1, 13)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)
print(np.sum(arr, axis=1))
print(np.mean(arr, axis=0))
print(np.reshape(arr, 12))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr>10])
arr[arr>10] = 0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [22]:
arr = np.array([120, 135, 110, 125, 130, 140])
print(f"{np.sum(arr)}")
print(f"{np.mean(arr):.3f}")
print(f"{np.var(arr):.3f}")
print(np.argmax(arr)+1)
print(np.argmin(arr)+1)

760
126.667
97.222
5
2


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a, b])
print(c)
print(np.reshape(c, (2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [31]:
arr = np.array([2, 1 ,2, 3, 1, 4, 3])
uarr, counts = np.unique(arr, return_counts=True)
print(uarr)
print(counts)


[1 2 3 4]
[2 2 2 1]
