In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.8.0+cpu


In [22]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
r = torch.arange(0, 10)
r

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Exercises

In [1]:
import torch

In [4]:
# 2 Create a random tensor with shape (7, 7).
t = torch.rand(7, 7)
t

torch.Size([7, 7])

In [10]:
# 3 Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

t2 = torch.rand(1, 7)
tt2 = torch.matmul(t, t2.T)
tt2, tt2.shape

(tensor([[1.0833],
         [2.2112],
         [1.8501],
         [1.9364],
         [0.8674],
         [1.3748],
         [1.4039]]),
 torch.Size([7, 1]))

In [13]:
# 4 Set the random seed to 0 and do 2 & 3 over again.
torch.manual_seed(0)
t = torch.rand(7, 7)
t2 = torch.rand(1, 7)
tt2 = torch.matmul(t, t2.T)
tt2, tt2.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [16]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
# If there is, set the GPU random seed to 1234.
hasGpu = torch.cuda.is_available()
if hasGpu:
    torch.cuda.manual_seed(1234)


In [44]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
# Device: cuda
# (tensor([[0.0290, 0.4019, 0.2598],
#          [0.3666, 0.0583, 0.7006]], device='cuda:0'),
#  tensor([[0.0518, 0.4681, 0.6738],
#          [0.3315, 0.7837, 0.5631]], device='cuda:0'))
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
if not hasGpu:
    torch.cuda.manual_seed(1234)
    tensor = torch.rand(2, 3).to(device)
    print(tensor)



cpu
tensor([[0.7204, 0.0731, 0.9699],
        [0.1078, 0.8829, 0.4132]])


In [24]:
# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
# The output should look like:

# (tensor([[0.3647, 0.4709],
#          [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

t = torch.rand(3, 2)
tt = torch.matmul(tensor, t)
tt


tensor([[1.2161, 1.1334],
        [0.5939, 0.1401]])

In [45]:
# 8. Find the maximum and minimum values of the output of 7.
max = tt.max()
min = tt.min()
min, max

(tensor(0.1401), tensor(1.2161))

In [29]:
# 9. Find the maximum and minimum index values of the output of 7.
max_index = tt.argmax()
min_index = tt.argmin()
min_index, max_index

tensor(3)

In [47]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
# The output should look like:

# tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
#            0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
# tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
#         0.8513]) torch.Size([10])

torch.manual_seed(7)

t = torch.rand(1, 1, 1, 10)
print(t, t.shape)

# remove single demensions
t2 = t.squeeze()
t2, t2.shape


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))